apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgptx
  labels:
    app: chatgptx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgptx
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chatgptx
    spec:
      containers:
        - image: dadaloser/chatgptx
          name: chatgptx
          imagePullPolicy: Always
          ports:
            - containerPort: 5438
          env:
            - name: OPENAI_API_KEY
              value: sk-xxx
            - name: OPENAI_API_BASE_URL
              value: 'https://api.openai.com'
            - name: OPENAI_API_MODEL
              value: gpt-3.5-turbo
            - name: API_REVERSE_PROXY
              value: https://ai.fakeopen.com/api/conversation
            - name: AUTH_SECRET_KEY
              value: ''
            - name: TIMEOUT_MS
              value: '100000'
            - name: SOCKS_PROXY_HOST
              value: ''
            - name: SOCKS_PROXY_PORT
              value: ''
            - name: HTTPS_PROXY
              value: ''
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 300m
              memory: 600Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatgptx
  name: chatgptx
spec:
  ports:
    - name: chatgptx
      port: 5438
      protocol: TCP
      targetPort: 5438
  selector:
    app: chatgptx
  type: ClusterIP
